
snd-asoc-dma-objs 	:= asoc-dma.o
snd-asoc-aic-objs 	:= asoc-aic.o
snd-asoc-i2s-objs 	:= asoc-i2s.o
snd-asoc-dmic-objs 	:= asoc-dmic.o
snd-asoc-spdif-objs 	:= asoc-spdif.o
snd-asoc-icdc-d3-objs := icodec/icdc_d3.o
snd-asoc-dump-codec-objs := icodec/dump.o
obj-$(CONFIG_SND_ASOC_INGENIC_DUMP_CODEC) += snd-asoc-dump-codec.o
obj-$(CONFIG_SND_ASOC_INGENIC_DMIC) += snd-asoc-dmic.o

obj-$(CONFIG_SND_ASOC_PDMA) += snd-asoc-dma.o
obj-$(CONFIG_SND_ASOC_INGENIC_AIC) += snd-asoc-aic.o
obj-$(CONFIG_SND_ASOC_INGENIC_AIC_I2S) += snd-asoc-i2s.o
obj-$(CONFIG_SND_ASOC_INGENIC_AIC_SPDIF) += snd-asoc-spdif.o

obj-$(CONFIG_SND_ASOC_INGENIC_ICDC_D3) += snd-asoc-icdc-d3.o

snd-soc-x1000-board-objs  := x1000-board.o

obj-$(CONFIG_SND_ASOC_INGENIC_X1000_BOARD) += snd-soc-x1000-board.o
